repo_name: gerageragera39/kotaemon
repo_url: https://github.com/gerageragera39/kotaemon
site_name: KURAG Documentation
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - About: about.md
  - Project Overview: project_overview.md
  - Guest Guide: guest_guide.md
  - Admin Guide: admin_guide.md
  - Usage: usage.md
  - Local Models: local_model.md
  - Evaluation: evaluation.md
  - Development: development.md
  - Attribution: attribution.md
  - Upstream Kotaemon:
      - Source: https://github.com/Cinnamon/kotaemon
      - Releases: https://github.com/Cinnamon/kotaemon/releases

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      title: Page contents
  - mdx_truly_sane_lists

plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/generate_reference_docs.py
  - literate-nav:
      nav_file: Summary.md
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: false
            filters:
              - "!^_"
            members_order: source
            separate_signature: true
          paths: [src/kotaemon]
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - section-index
  - mkdocs-video
  - include-markdown

theme:
  features:
    - content.action.edit
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - toc.follow
    - search.share
    - search.highlight
    - search.suggest
  name: material
  custom_dir: docs/theme
  palette:
    scheme: dracula
    primary: deep purple
    accent: deep purple
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

extra_css:
  - theme/assets/pymdownx-extras/extra-fb5a2a1c86.css

extra_javascript:
  - theme/assets/pymdownx-extras/extra-loader-MCFnu0Wd.js

validation:
  absolute_links: warn
  omitted_files: warn
  unrecognized_links: warn
