name: Auto Bump and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  auto-bump-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Application Version
        id: update-version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          MAJOR_STRING_TOKEN: "bump:major"
          MINOR_STRING_TOKEN: "bump:minor"
          PATCH_STRING_TOKEN: "bump:patch"
      - name: Create release for ${{ steps.update-version.outputs.new_tag }}
        # need to repeat this if statement because Github Action doesn't support early
        # stopping for steps
        if: ${{ steps.update-version.outputs.new_tag != steps.update-version.outputs.old_tag }}
        run: |
          echo Create release folder
          mkdir kuraga-app
          echo ${{ steps.update-version.outputs.new_tag }} > kuraga-app/VERSION
          cp LICENSE.txt kuraga-app/
          cp flowsettings.py kuraga-app/
          cp app.py kuraga-app/
          cp pyproject.toml kuraga-app/
          cp requirements_gerageragera39.txt kuraga-app/
          cp NOTICE.md kuraga-app/
          cp .env.example kuraga-app/.env
          cp -r scripts kuraga-app/
          cp -r src kuraga-app/
          cp -r docs kuraga-app/

          tree kuraga-app
          zip -r kuraga-app.zip kuraga-app
      - name: Release ${{ steps.update-version.outputs.new_tag }}
        if: ${{ steps.update-version.outputs.new_tag != steps.update-version.outputs.old_tag }}
        uses: softprops/action-gh-release@v2
        with:
          files: kuraga-app.zip
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          tag_name: ${{ steps.update-version.outputs.new_tag }}
          make_latest: true
      - name: Setup latest branch locally without switching current branch
        if: ${{ steps.update-version.outputs.new_tag != steps.update-version.outputs.old_tag }}
        run: git fetch origin latest:latest
      - name: Update latest branch
        if: ${{ steps.update-version.outputs.new_tag != steps.update-version.outputs.old_tag }}
        run: |
          git branch -f latest tags/${{ steps.update-version.outputs.new_tag }}
          git checkout latest
          git push -f -u origin latest
